# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-03 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
    ]
