# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-04 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tao', '0002_remove_user_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
